name: Java CI with Maven

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test with Maven
        run: mvn clean install

  - name: Notify on PR creation
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    run: |
      curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
        -H 'Content-type: application/json' \
        --data "{
          \"text\": \"📣 *New Pull Request Created*\n*Repo:* ${{ github.repository }}\n*Author:* ${{ github.actor }}\n*Link:* ${{ github.event.pull_request.html_url }}\"
        }"

  - name: Notify on Build Failure
    if: failure()
    run: |
      curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
        -H 'Content-type: application/json' \
        --data "{
          \"text\": \"❌ *Build Failed*\n*Repo:* ${{ github.repository }}\n*Actor:* ${{ github.actor }}\n*Workflow:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
        }"
